# .github/dependabot.yml
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
      - "automerge"   # Safe to merge automatically

  # Python dependencies (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly" # normal updates weekly, but security PRs are immediate
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
      security:
        applies-to: security-updates
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "security"
      - "automerge"   # Minor/patch + security auto-merge
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-major"] # keep majors manual

  # Dockerfile base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      all-docker-updates:
        patterns: ["*"]
    labels:
      - "dependencies"
      - "automerge"