# .github/dependabot.yml
version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
      - "automerge"

  # Python dependencies (requirements.txt) - normal updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-type: "direct"
        update-types: ["major"]
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
      - "automerge"

  # Python dependencies (requirements.txt) - security updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "security"
      - "automerge"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      all-docker-updates:
        patterns: ["*"]
    labels:
      - "dependencies"
      - "automerge"