version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
      - "automerge"

  # Weekly Python dependency updates (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "automerge"

  # Daily security-focused Python updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "security"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "security"
      - "automerge"

  # Keep Dockerfile base images up to date
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      all-docker-updates:
        patterns: ["*"]
    labels:
      - "dependencies"
      - "automerge"