# .github/dependabot.yml
version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]
    labels: ["dependencies", "automerge"]

  # Keep Python deps (requirements.txt) up to date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"     # security PRs still come ASAP
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    ignore:
      # Block all major bumps from auto-PRs (you can handle majors manually)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
    labels: ["dependencies", "security", "automerge"]

  # Keep Docker base images up to date
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      all-docker-updates:
        patterns: ["*"]
    labels: ["dependencies", "automerge"]