# .github/dependabot.yml
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
      - "automerge"

  # Python - security updates (daily)
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "automerge"
    allow:
      - dependency-type: "direct"

  # Python - regular updates (weekly)
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
      - "automerge"
    allow:
      - dependency-type: "direct"

  # Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      all-docker-updates:
        patterns: ["*"]
    labels:
      - "dependencies"
      - "automerge"