name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Fixes
    labels:
      - bug
      - fix
  - title: 🛠 Maintenance
    labels:
      - chore
      - refactor
      - docs
      - dependencies

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  ## Changes
  $CHANGES

empty-template: "No notable changes in this release."

sort: "ASC"