version: "3.9"

services:
  syncmover:
    image: lebowski89/syncmover:latest
    container_name: syncmover
    restart: unless-stopped
    environment:
      # Syncthing API
      SYNCTHING_API_KEY_FILE: /run/secrets/syncthing_api_key
      SYNCTHING_HOST: "127.0.0.1"
      SYNCTHING_PORT: "8384"
      API_TIMEOUT: "15"

      # Logging
      LOG_FILE: "/logs/syncmover.log"
      LOG_LEVEL: "INFO"
      LOG_ROTATE_SIZE: "5242880"
      LOG_ROTATE_BACKUP: "5"
      DRY_RUN: "false"

      # Cleanup
      CLEANUP_AFTER_HOURS: "24"
      CLEANUP_INTERVAL_MINUTES: "360"
      CLEANUP_BATCH_SIZE: "100"
      KEEP_RECENT_FILES: "10"
      GRACE_PERIOD_MINUTES: "15"
      LOG_GRACE_PERIOD_SKIPS: "true"

      # File ownership
      OWNER_UID: "1000"
      OWNER_GID: "1000"

      # Ignore files
      IGNORE_FILES: ".stfolder"
      IGNORE_PATTERNS: ".syncthing.,.tmp"

      # Folder mappings
      #
      # You can add as many folders as you need, just follow the pattern:
      # <FOLDERNAME>_<INDEX>_LABEL
      # <FOLDERNAME>_<INDEX>_SYNC_PATH
      # <FOLDERNAME>_<INDEX>_MOVER_PATH
      #
      MOVIES_0_LABEL: "Movies"
      MOVIES_0_SYNC_PATH: "/data/sync/movies"
      MOVIES_0_MOVER_PATH: "/data/media/movies"

      MOVIES_1_LABEL: "Movies-4K"
      MOVIES_1_SYNC_PATH: "/data/sync/movies-4k"
      MOVIES_1_MOVER_PATH: "/data/media/movies-4k"

      TV_0_LABEL: "TVShows"
      TV_0_SYNC_PATH: "/data/sync/tv"
      TV_0_MOVER_PATH: "/data/media/tv"

    volumes:
      - /host/data:/data
      - /host/logs:/logs

    secrets:
      - syncthing_api_key

secrets:
  syncthing_api_key:
    file: ./secrets/syncthing_api_key.txt