name: Dependabot Auto Merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: contains(github.event.pull_request.user.login, 'dependabot[bot]') && contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Dependabot PRs
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash