name: Dependabot Auto Label

on:
  pull_request:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Add automerge label to Dependabot PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge