name: Sync GitHub Labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00 UTC

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync labels
        uses: softprops/labels@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels.yml
          remove-extra-labels: true